version: '3.4'

services:
  guest-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  host-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
        - "80"
        - "443"
  logs:
    volumes:
      - C:/DockerVolumes/Seq:/data
  rabbitmq:
    volumes:
        - C:/DockerVolumes/RabbitMq/data/:/var/lib/rabbitmq/
        - C:/DockerVolumes/RabbitMq/log/:/var/log/rabbitmq
  host-domain:
    environment:
      - ConnectionStrings__RabbitMq=rabbitmq
      - ConnectionStrings__MongoDb=mongodb://mongodb
      - Serilog__WriteTo__1__Args__serverUrl=http://logs