version: '3.4'

services:
  guest-api:
    image: ${DOCKER_REGISTRY-}guestapi
    build:
      context: .
      dockerfile: guest-api/Dockerfile
    ports:
        - "9005:80"
        - "9006:443"
    depends_on:
      - "logs"
  host-api:
    image: ${DOCKER_REGISTRY-}hostapi
    build:
      context: .
      dockerfile: host-api/Dockerfile
    ports:
        - "9011:80"
        - "9012:443"
    depends_on:
      - "logs"
  logs:
    image: datalust/seq
    volumes:
      - C:/logdata:/data
    ports:
        - "9021:80"
    environment:
      - ACCEPT_EULA=Y