version: '3.4'

services:
  guest-api:
    image: ${DOCKER_REGISTRY-}guestapi
    build:
      context: .
      dockerfile: guest-api/Dockerfile
    ports:
        - "9005:80"
        - "9006:443"
    depends_on:
      - "logs"
      - "rabbitmq"
      - "mongodb"
  host-api:
    image: ${DOCKER_REGISTRY-}hostapi
    build:
      context: .
      dockerfile: host-api/Dockerfile
    ports:
        - "9011:80"
        - "9012:443"
    depends_on:
      - "logs"
      - "rabbitmq"
      - "mongodb"
  host-domain:
    image: ${DOCKER_REGISTRY-}hostdomain
    build:
      context: .
      dockerfile: host-domain/Dockerfile
    depends_on:
      - "logs"
      - "rabbitmq"
      - "mongodb"
  host-projections:
    image: ${DOCKER_REGISTRY-}hostprojections
    build:
      context: .
      dockerfile: host-projections/Dockerfile
    depends_on:
      - "logs"
      - "rabbitmq"
      - "mongodb"
  logs:
    image: datalust/seq
    volumes:
      - /DockerVolumes/Seq:/data
    ports:
        - "9021:80"
    environment:
      - ACCEPT_EULA=Y
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - /DockerVolumes/RabbitMq/data/:/var/lib/rabbitmq/
        - /DockerVolumes/RabbitMq/log/:/var/log/rabbitmq
  mongodb:
    image: mongo
    ports:
        - 27017:27017
    volumes:
        - /DockerVolumes/MongoDb/db:/data/db
        - /DockerVolumes/MongoDb/configdb:/data/configdb
