---
apiVersion: v1
kind: Service
metadata:
  name: room-booking-host-domain-svc
  namespace: room-booking-host
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: room-booking-host-domain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-booking-host-domain
  namespace: room-booking-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-booking-host-domain
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: room-booking-host-domain
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: room-booking-host-domain
        image: michaelhorsley/room-booking-host-domain:<VERSION_NUMBER>
        imagePullPolicy: IfNotPresent
        resources:
            limits:
              memory: 1Gi
        env:
          - name: Serilog__WriteTo__1__Args__serverUrl
            valueFrom:
              secretKeyRef:
                name: host-secrets
                key: seq-url
                optional: false
          - name: ConnectionStrings__RabbitMq
            valueFrom:
              secretKeyRef:
                name: host-secrets
                key: rabbitmq
                optional: false
          - name: ConnectionStrings__MongoDb
            valueFrom:
              secretKeyRef:
                name: host-secrets
                key: mongodb
                optional: false
